name: Skip tests

on:
  push:
    paths-ignore:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No testing required"'
