# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run tests

on:
  push:
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: ''
    # npm ci will use package-lock, we cannot use package lock because every NPM will have own package signature
    - run: npm i
    - run: npm test
